name: Horus Firmware Derle ve Yayınla

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  derle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Depoyu Çek
      - name: Satır Sonlarını LF’ye Dönüştür
        run: |
          echo "Dosya satır sonları LF’ye dönüştürülüyor..."
          if [ -f WyntroHorus2.ino ]; then
            sed -i 's/\r$//' WyntroHorus2.ino
          else
            echo "Hata: WyntroHorus2.ino bulunamadı, satır sonu dönüştürmesi atlandı."
          fi
      - name: Arduino CLI’yi Kur
        uses: arduino/setup-arduino-cli@v1
      - name: ESP32 Platformunu Kur
        run: |
          echo "ESP32 platformu kuruluyor..."
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.0
      - name: Kütüphaneleri Kur
        run: |
          echo "Kütüphaneler kuruluyor..."
          arduino-cli lib install "WebSockets@2.6.1"
          arduino-cli lib install "ElegantOTA@3.1.7"
          arduino-cli lib install "ArduinoJson@7.4.2"
      - name: Firmware Sürümünü Çıkar ve Artır
        run: |
          echo "Dosya varlığı kontrol ediliyor..."
          if [ ! -f WyntroHorus2.ino ]; then
            echo "Hata: WyntroHorus2.ino dosyası bulunamadı!"
            exit 1
          fi
          echo "WyntroHorus2.ino içeriği kontrol ediliyor..."
          cat WyntroHorus2.ino | grep 'FIRMWARE_VERSION'
          echo "grep komutu çalışıyor..."
          VERSION=$(grep -E '^[[:space:]]*const[[:space:]]+char[[:space:]]*\*[[:space:]]*FIRMWARE_VERSION[[:space:]]*=' WyntroHorus2.ino | grep -o '"v[0-9]+\\.[0-9]+\\.[0-9]+"' | tr -d '"' || echo "")
          echo "grep çıktısı: VERSION=$VERSION"
          if [ -z "$VERSION" ]; then
            echo "Hata: FIRMWARE_VERSION bulunamadı veya format yanlış!"
            echo "Beklenen format: const char* FIRMWARE_VERSION = \"vX.Y.Z\";"
            echo "Bulunan satırlar:"
            grep 'FIRMWARE_VERSION' WyntroHorus2.ino || echo "Hiçbir eşleşme bulunamadı"
            echo "Dosya içeriği:"
            cat WyntroHorus2.ino
            exit 1
          fi
          echo "Mevcut sürüm: $VERSION"
          IFS='.' read -r -a PARTS <<< "${VERSION#v}"
          if [ ${#PARTS[@]} -ne 3 ]; then
            echo "Hata: Sürüm formatı vX.Y.Z olmalı, bulunan: $VERSION"
            exit 1
          fi
          PATCH=$((PARTS[2] + 1))
          NEW_VERSION="v${PARTS[0]}.${PARTS[1]}.$PATCH"
          echo "Yeni sürüm: $NEW_VERSION"
          sed -i "s/const[[:space:]]*char[[:space:]]*\*[[:space:]]*FIRMWARE_VERSION[[:space:]]*=[[:space:]]*\"v[0-9.]*\"/const char* FIRMWARE_VERSION = \"$NEW_VERSION\"/" WyntroHorus2.ino
          echo "Dosya değişikliği kontrol ediliyor..."
          if git diff --exit-code WyntroHorus2.ino; then
            echo "Uyarı: WyntroHorus2.ino’da değişiklik yok, commit atlanıyor."
            echo "FIRMWARE_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          else
            echo "FIRMWARE_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add WyntroHorus2.ino
            git commit -m "Firmware sürümü $NEW_VERSION’a yükseltildi"
          fi
      - name: Kodu Derle
        run: |
          echo "Kod derleniyor..."
          arduino-cli compile --fqbn esp32:esp32:esp32 --build-path ./build WyntroHorus2.ino
      - name: Derleme Çıktısını Kontrol Et
        run: |
          echo "Derleme dizini içeriği:"
          ls -la ./build
      - name: Binary Dosyasını Yeniden Adlandır
        run: |
          echo "Binary dosyası yeniden adlandırılıyor..."
          if [ -f ./build/WyntroHorus2.ino.bin ]; then
            mv ./build/WyntroHorus2.ino.bin ./build/wyntrohorus2-${{ env.FIRMWARE_VERSION }}.bin
          else
            echo "Hata: Binary dosyası bulunamadı!"
            ls -la ./build
            exit 1
          fi
      - name: Yeni Sürümü GitHub’a Yükle
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/wyntrohorus2-${{ env.FIRMWARE_VERSION }}.bin
          tag_name: ${{ env.FIRMWARE_VERSION }}
          body: |
            Yeni firmware sürümü: ${{ env.FIRMWARE_VERSION }}
            - Otomatik derleme ve OTA desteği
            - WiFi tarama ve motor kontrolü iyileştirmeleri
