name: Build and Release Horus Firmware

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install ESP32 platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.0
      - name: Install libraries
        run: |
          arduino-cli lib install "WebSockets@2.6.1"
          arduino-cli lib install "ElegantOTA@3.1.7"
          arduino-cli lib install "ArduinoJson@7.4.2"
      - name: Build sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --build-path ./build WyntroHorus2.ino
      - name: Debug build output
        run: |
          echo "Build dizini içeriği:"
          ls -la ./build
      - name: Rename binary
        run: |
          if [ -f ./build/WyntroHorus2.ino.bin ]; then
            mv ./build/WyntroHorus2.ino.bin ./build/wyntrohorus2-v${{ github.sha }}.bin
          else
            echo "Binary dosyası bulunamadı!"
            ls -la ./build
            exit 1
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/wyntrohorus2-v${{ github.sha }}.bin
          tag_name: v${{ github.sha }}
