name: Horus Firmware Derle ve Yayınla

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  derle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Depoyu Çek
      - name: Arduino CLI’yi Kur
        uses: arduino/setup-arduino-cli@v1
      - name: ESP32 Platformunu Kur
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.0
      - name: Kütüphaneleri Kur
        run: |
          arduino-cli lib install "WebSockets@2.6.1"
          arduino-cli lib install "ElegantOTA@3.1.7"
          arduino-cli lib install "ArduinoJson@7.4.2"
      - name: Firmware Sürümünü Çıkar ve Artır
        run: |
          VERSION=$(grep 'const char.*FIRMWARE_VERSION' WyntroHorus2.ino | grep -o '"v[0-9.]*"' | tr -d '"')
          IFS='.' read -r -a PARTS <<< "${VERSION#v}"
          PATCH=$((PARTS[2] + 1))
          NEW_VERSION="v${PARTS[0]}.${PARTS[1]}.$PATCH"
          sed -i "s/const char\* FIRMWARE_VERSION = \"v[0-9.]*\"/const char* FIRMWARE_VERSION = \"$NEW_VERSION\"/" WyntroHorus2.ino
          echo "FIRMWARE_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add WyntroHorus2.ino
          git commit -m "Firmware sürümü $NEW_VERSION’a yükseltildi"
      - name: Kodu Derle
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --build-path ./build WyntroHorus2.ino
      - name: Derleme Çıktısını Kontrol Et
        run: |
          echo "Derleme dizini içeriği:"
          ls -la ./build
      - name: Binary Dosyasını Yeniden Adlandır
        run: |
          if [ -f ./build/WyntroHorus2.ino.bin ]; then
            mv ./build/WyntroHorus2.ino.bin ./build/wyntrohorus2-${{ env.FIRMWARE_VERSION }}.bin
          else
            echo "Binary dosyası bulunamadı!"
            ls -la ./build
            exit 1
          fi
      - name: Sürümü Yayınla
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/wyntrohorus2-${{ env.FIRMWARE_VERSION }}.bin
          tag_name: ${{ env.FIRMWARE_VERSION }}
